### ISSUE TITLE
Error: set the 'IDEMPIERE_REPOSITORY' env variable first                                                                                              

### ISSUE THREAD

**Issue by djoudi** [ingeint/idempiere-plugin-scaffold#1]
.\build.bat
Source Idempiere : C:\Users\Djoudi\Source\DevRepo
plugin : C:\Users\Djoudi\Source\idempiere-plugin-scaffold-master\dz.test.plugin

Error: set the 'IDEMPIERE_REPOSITORY' env variable first                                                                                              
[INFO] Scanning for projects...                                                                                                                       
[INFO] ------------------------------------------------------------------------                                                                       
[INFO] BUILD FAILURE                                                                                                                                  
[INFO] ------------------------------------------------------------------------                                                                       
[INFO] Total time:  0.189 s                                                                                                                           
[INFO] Finished at: 2020-02-05T05:41:41+01:00                                                                                                         
[INFO] ------------------------------------------------------------------------                                                                       
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\Djoudi\Source\idempiere-plugin-scaffold-m
aster\dz.test.plugin\dz.test.plugin.targetplatform). Please verify you invoked Maven from the correct directory. -> [Help 1]                
[ERROR]                                                                                                                                               
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                                   
[ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                                                
[ERROR]                                                                                                                                               
[ERROR] For more information about the errors and possible solutions, please read the following articles:                                             
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException                                                             
Exception in thread "main" java.lang.NullPointerException                                                                                             
        at TargetPlatformPluginTagger.copyJars(TargetPlatformPluginTagger.java:30)                                                                    
        at TargetPlatformPluginTagger.main(TargetPlatformPluginTagger.java:23)

**Comment by djoudi** [comment]
@sauljabin
