### ISSUE TITLE
java.nio.file.InvalidPathException running build.bat

### ISSUE THREAD

**Issue by asiemsuk** [ingeint/idempiere-plugin-scaffold#3]
Running the build script from Windows 10 command prompt, is returning the following exception:

`'cmd' is not recognized as an internal or external command,
operable program or batch file.
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 21: org.roca.ws;singleton:=true-8.2.0.202106171437.jar
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.resolve(Path.java:515)
        at TargetPlatformPluginTagger.copyJars(TargetPlatformPluginTagger.java:39)
        at TargetPlatformPluginTagger.main(TargetPlatformPluginTagger.java:23)`

**Comment by sauljabin** [comment]
Hi thanks for reporting, when generating the jar we added a post process for creating a dated jar, but it is failing on singleton plugins, although we know how to fix it, kee in touch
